<a href="https://colab.research.google.com/github/alex3181/pytorch-tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np


**Lists**

In [4]:
my_list=[1,2,3,4,5,6]
my_list
my_multi_list=[[1,2,3,4,5],[6,7,8,9,10]]
my_multi_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

**Numpy Arrays**

In [17]:
np1=np.random.rand(3,4)
print(np1)
print(np1.dtype)

[[0.81332292 0.85954223 0.62441389 0.04077091]
 [0.76076837 0.15258038 0.10917812 0.1465255 ]
 [0.33756666 0.73112716 0.48167312 0.21789518]]
float64


**Tensors**

In [18]:
tensor_2d=torch.rand(3,4)
print(type(tensor_2d))
print(tensor_2d)
print(tensor_2d.dtype)

<class 'torch.Tensor'>
tensor([[0.9467, 0.4217, 0.7754, 0.7195],
        [0.5842, 0.9792, 0.7580, 0.6045],
        [0.6030, 0.1054, 0.9334, 0.3042]])
torch.float32


In [19]:
my_tensor=torch.tensor(np1)
print(type(my_tensor))
my_tensor

<class 'torch.Tensor'>


tensor([[0.8133, 0.8595, 0.6244, 0.0408],
        [0.7608, 0.1526, 0.1092, 0.1465],
        [0.3376, 0.7311, 0.4817, 0.2179]], dtype=torch.float64)

**-- Tensor Operations --**

In [20]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# Reshape and view
my_torch=my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])